### ISSUE TITLE
Allow `--ignore-packages` to take a semver range filter, not just an exact match

### ISSUE THREAD

**Issue by thislooksfun** [jens-duttke/check-outdated#16]
I maintain a few open source repos, and I am not ready to port any of them to ESM-only just yet. However, several of the dependencies that I use _are_ switching to ESM only. This means that I can't update them past a certain point, but I still want to check if there are any security/backported fixes available. For these packages it would be great if I could use a [semver](https://www.npmjs.com/package/semver) range to select versions to ignore. For example, saying `--ignore-packages got@^12` would ignore all 12.x releases of the `got` package, but still show 11.x patches and alert me if/when 13.x is released, without me having to continually update the ignored version every time it updates.

**Comment by jens-duttke** [comment]
Thanks for this suggestion. I have just released a new version that allows you to use such ranges.

**Comment by thislooksfun** [comment]
Wow, that was fast! Thank you!
